[package]
name    = "afrim_capi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
afrim-config       = { path = "../../afrim/config", version = "0.4.7" }
afrim-preprocessor = { path = "../../afrim/engine/preprocessor", version = "0.6.3" }
afrim-translator   = { path = "../../afrim/engine/translator", version = "0.2.3" }
indexmap           = "2"

[features]
default = ["rhai", "strsim"]
inhibit = ["afrim-preprocessor/inhibit"]
rhai = ["afrim-config/rhai", "afrim-translator/rhai"]
strsim = ["afrim-translator/strsim"]
