name: CMake on a single platform
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: pacman -Sy --noconfirm base-devel abuild rpm-tools dpkg extra-cmake-modules cmake fcitx5 rust cargo

    - name: Build and install corrosion
      run: |
        git clone --depth 1 https://github.com/corrosion-rs/corrosion.git
        cmake -S corrosion -B corrosion/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build corrosion/build --config ${{env.BUILD_TYPE}}
        cmake --install corrosion/build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Release
      run: cd ${{github.workspace}}/build && cpack -C ${{ env.BUILD_TYPE }} -G "DEB;RPM;STGZ"
